import type * as MonacoEditor from 'monaco-editor';

// Define our themes collection. These will be injected into Monaco on mount.
export const THEMES: Record<string, MonacoEditor.editor.IStandaloneThemeData> = {
  dracula: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '282a36', token: '' },
      { foreground: '6272a4', token: 'comment' },
      { foreground: 'f1fa8c', token: 'string' },
      { foreground: 'bd93f9', token: 'constant.numeric' },
      { foreground: 'bd93f9', token: 'constant.language' },
      { foreground: 'bd93f9', token: 'constant.character' },
      { foreground: 'bd93f9', token: 'constant.other' },
      { foreground: 'ffb86c', token: 'variable.other.readwrite.instance' },
      { foreground: 'ff79c6', token: 'constant.character.escape' },
      { foreground: '50fa7b', token: 'variable.parameter' },
      { foreground: 'ff79c6', token: 'keyword' },
      { foreground: 'ff79c6', token: 'storage' },
      { foreground: '8be9fd', fontStyle: 'italic', token: 'storage.type' },
      { foreground: '50fa7b', fontStyle: 'underline', token: 'entity.name.class' },
      { foreground: '50fa7b', fontStyle: 'italic underline', token: 'entity.other.inherited-class' },
      { foreground: '50fa7b', token: 'entity.name.function' },
      { foreground: '8be9fd', fontStyle: 'italic', token: 'variable.parameter' },
      { foreground: 'ff79c6', token: 'entity.name.tag' },
      { foreground: '50fa7b', token: 'entity.other.attribute-name' },
      { foreground: '8be9fd', token: 'support.function' },
      { foreground: '6be5fd', token: 'support.constant' },
      { foreground: '66d9ef', fontStyle: 'italic', token: 'support.type' },
      { foreground: '66d9ef', fontStyle: 'italic', token: 'support.class' },
      { foreground: 'f8f8f0', background: 'ff79c6', token: 'invalid' },
      { foreground: 'f8f8f0', background: 'bd93f9', token: 'invalid.deprecated' },
      { foreground: 'cfcfc2', token: 'meta.structure.dictionary.json string.quoted.double.json' },
      { foreground: '6272a4', token: 'meta.diff' },
      { foreground: '6272a4', token: 'meta.diff.header' },
      { foreground: 'ff79c6', token: 'markup.deleted' },
      { foreground: '50fa7b', token: 'markup.inserted' },
      { foreground: 'e6db74', token: 'markup.changed' }
    ],
    colors: {
      'editor.foreground': '#f8f8f2',
      'editor.background': '#282a36',
      'editor.selectionBackground': '#44475a',
      'editor.lineHighlightBackground': '#44475a',
      'editorCursor.foreground': '#f8f8f0',
      'editorWhitespace.foreground': '#3B3A32',
      'editorIndentGuide.activeBackground': '#9D550FB0',
      'editor.selectionHighlightBorder': '#222218'
    }
  },
  monokai: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '272822', token: '' },
      { foreground: '75715e', token: 'comment' },
      { foreground: 'e6db74', token: 'string' },
      { foreground: 'ae81ff', token: 'constant.numeric' },
      { foreground: 'ae81ff', token: 'constant.language' },
      { foreground: 'ae81ff', token: 'constant.character' },
      { foreground: 'ae81ff', token: 'constant.other' },
      { foreground: 'f92672', token: 'keyword' },
      { foreground: 'f92672', token: 'storage' },
      { foreground: '66d9ef', fontStyle: 'italic', token: 'storage.type' },
      { foreground: 'a6e22e', fontStyle: 'underline', token: 'entity.name.class' },
      { foreground: 'a6e22e', fontStyle: 'italic underline', token: 'entity.other.inherited-class' },
      { foreground: 'a6e22e', token: 'entity.name.function' },
      { foreground: 'fd971f', fontStyle: 'italic', token: 'variable.parameter' },
      { foreground: 'f92672', token: 'entity.name.tag' },
      { foreground: 'a6e22e', token: 'entity.other.attribute-name' },
      { foreground: '66d9ef', token: 'support.function' },
      { foreground: '66d9ef', token: 'support.constant' },
      { foreground: '66d9ef', fontStyle: 'italic', token: 'support.type' },
      { foreground: '66d9ef', fontStyle: 'italic', token: 'support.class' },
      { foreground: 'f8f8f0', background: 'f92672', token: 'invalid' },
      { foreground: 'f8f8f0', background: 'ae81ff', token: 'invalid.deprecated' },
      { foreground: 'cfcfc2', token: 'meta.structure.dictionary.json string.quoted.double.json' },
      { foreground: '75715e', token: 'meta.diff' },
      { foreground: '75715e', token: 'meta.diff.header' },
      { foreground: 'f92672', token: 'markup.deleted' },
      { foreground: 'a6e22e', token: 'markup.inserted' },
      { foreground: 'e6db74', token: 'markup.changed' }
    ],
    colors: {
      'editor.foreground': '#f8f8f2',
      'editor.background': '#272822',
      'editor.selectionBackground': '#49483e',
      'editor.lineHighlightBackground': '#3e3d32',
      'editorCursor.foreground': '#f8f8f0',
      'editorWhitespace.foreground': '#3B3A32',
      'editorIndentGuide.activeBackground': '#9D550FB0',
      'editor.selectionHighlightBorder': '#222218'
    }
  },
  'github-dark': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '24292e', token: '' },
      { foreground: '6a737d', token: 'comment' },
      { foreground: '6a737d', token: 'punctuation.definition.comment' },
      { foreground: '6a737d', token: 'string.comment' },
      { foreground: 'c8e1ff', token: 'constant' },
      { foreground: 'c8e1ff', token: 'entity.name.constant' },
      { foreground: 'c8e1ff', token: 'variable.other.constant' },
      { foreground: 'c8e1ff', token: 'variable.language' },
      { foreground: 'b392f0', token: 'entity' },
      { foreground: 'b392f0', token: 'entity.name' },
      { foreground: 'f6f8fa', token: 'variable.parameter.function' },
      { foreground: '79b8ff', token: 'entity.name.tag' },
      { foreground: 'ea4a5a', token: 'keyword' },
      { foreground: 'ea4a5a', token: 'storage' },
      { foreground: 'ea4a5a', token: 'storage.type' },
      { foreground: 'f6f8fa', token: 'storage.modifier.package' },
      { foreground: 'f6f8fa', token: 'storage.modifier.import' },
      { foreground: 'f6f8fa', token: 'storage.type.java' },
      { foreground: '9bc53d', token: 'string' },
      { foreground: '9bc53d', token: 'punctuation.definition.string' },
      { foreground: '9bc53d', token: 'string punctuation.section.embedded source' },
      { foreground: 'c8e1ff', token: 'support' },
      { foreground: 'c8e1ff', token: 'meta.property-name' },
      { foreground: 'fb8532', token: 'variable' },
      { foreground: 'f6f8fa', token: 'variable.other' },
      { foreground: 'b392f0', background: 'ea4a5a', token: 'invalid.broken' },
      { foreground: 'b392f0', background: 'ea4a5a', token: 'invalid.deprecated' },
      { foreground: 'b392f0', background: 'ea4a5a', token: 'invalid.illegal' },
      { foreground: 'b392f0', background: 'ea4a5a', token: 'invalid.unimplemented' },
      { foreground: 'fafbfc', background: 'ea4a5a', token: 'carriage-return' },
      { foreground: 'b392f0', background: 'ea4a5a', token: 'message.error' },
      { foreground: 'c8e1ff', token: 'string source' },
      { foreground: 'c8e1ff', token: 'string variable' },
      { foreground: '79b8ff', token: 'source.regexp' },
      { foreground: '79b8ff', token: 'string.regexp' },
      { foreground: '79b8ff', token: 'string.regexp.character-class' },
      { foreground: '79b8ff', token: 'string.regexp constant.character.escape' },
      { foreground: '79b8ff', token: 'string.regexp source.ruby.embedded' },
      { foreground: '79b8ff', token: 'string.regexp string.regexp.arbitrary-repitition' },
      { fontStyle: 'bold', token: 'string.regexp constant.character.escape' },
      { foreground: '9bc53d', token: 'support.constant' },
      { foreground: 'c8e1ff', token: 'support.variable' },
      { foreground: 'c8e1ff', token: 'meta.module-reference' },
      { foreground: 'fb8532', token: 'markup.list' },
      { foreground: '0366d6', fontStyle: 'bold', token: 'markup.heading' },
      { foreground: '0366d6', fontStyle: 'bold', token: 'markup.heading entity.name' },
      { foreground: 'c8e1ff', token: 'markup.quote' },
      { fontStyle: 'italic', token: 'markup.italic' },
      { fontStyle: 'bold', token: 'markup.bold' },
      { foreground: 'c8e1ff', token: 'markup.raw' },
      { foreground: 'b31d28', background: 'ffeef0', token: 'markup.deleted' },
      { foreground: 'b31d28', background: 'ffeef0', token: 'meta.diff.header.from-file' },
      { foreground: 'b31d28', background: 'ffeef0', token: 'punctuation.definition.deleted' },
      { foreground: '22863a', background: 'f0fff4', token: 'markup.inserted' },
      { foreground: '22863a', background: 'f0fff4', token: 'meta.diff.header.to-file' },
      { foreground: '22863a', background: 'f0fff4', token: 'punctuation.definition.inserted' },
      { foreground: 'e36209', background: 'ffebda', token: 'markup.changed' },
      { foreground: 'e36209', background: 'ffebda', token: 'punctuation.definition.changed' },
      { foreground: 'f6f8fa', background: '005cc5', token: 'markup.ignored' },
      { foreground: 'f6f8fa', background: '005cc5', token: 'markup.untracked' },
      { foreground: '735c0f', fontStyle: 'bold', token: 'meta.diff.range' },
      { foreground: '005cc5', token: 'meta.diff.header' },
      { foreground: '0366d6', fontStyle: 'bold', token: 'meta.separator' },
      { foreground: '0366d6', token: 'meta.output' }
    ],
    colors: {
      'editor.foreground': '#f6f8fa',
      'editor.background': '#24292e',
      'editor.selectionBackground': '#4c2889',
      'editor.inactiveSelectionBackground': '#444d56',
      'editor.lineHighlightBackground': '#444d56',
      'editorCursor.foreground': '#c8e1ff',
      'editorWhitespace.foreground': '#444d56',
      'editorIndentGuide.background': '#444d56',
      'editorIndentGuide.activeBackground': '#f6f8fa',
      'editor.selectionHighlightBorder': '#444d56'
    }
  },
  'night-owl': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '011627', token: '' },
      { foreground: '637777', fontStyle: 'italic', token: 'comment' },
      { foreground: 'addb67', token: 'string' },
      { foreground: 'ecc48d', token: 'vairable' },
      { foreground: '82aaff', token: 'keyword' },
      { foreground: 'c792ea', token: 'storage.type' },
      { foreground: 'ffcb6b', token: 'entity.name.class' },
      { foreground: 'ffcb6b', token: 'entity.name.type' },
      { foreground: '82aaff', token: 'entity.name.function' },
      { foreground: 'f78c6c', token: 'constant' },
      { foreground: '82aaff', token: 'constant.language' },
      { foreground: 'f78c6c', token: 'constant.numeric' },
      { foreground: 'd6deeb', token: 'variable.parameter' },
      { foreground: '7fdbca', token: 'entity.name.tag' },
      { foreground: 'addb67', fontStyle: 'italic', token: 'entity.other.attribute-name' },
      { foreground: '82aaff', token: 'support.function' },
      { foreground: 'addb67', token: 'support.constant' },
      { foreground: 'ffcb6b', token: 'support.type' },
      { foreground: 'ffcb6b', token: 'support.class' },
      { foreground: 'ffffff', background: 'ff2c83', token: 'invalid' }
    ],
    colors: {
      'editor.foreground': '#d6deeb',
      'editor.background': '#011627',
      'editor.selectionBackground': '#1d3b53',
      'editor.lineHighlightBackground': '#122d42',
      'editorCursor.foreground': '#80a4c2',
      'editorWhitespace.foreground': '#2e2040',
      'editorIndentGuide.background': '#5f7e97',
      'editorIndentGuide.activeBackground': '#084d81'
    }
  }
};
