// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/online-c-compiler": {
    params: {};
  };
  "/online-cpp-compiler": {
    params: {};
  };
  "/online-python-compiler": {
    params: {};
  };
  "/online-java-compiler": {
    params: {};
  };
  "/online-javascript-compiler": {
    params: {};
  };
  "/online-go-compiler": {
    params: {};
  };
  "/online-rust-compiler": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/online-c-compiler" | "/online-cpp-compiler" | "/online-python-compiler" | "/online-java-compiler" | "/online-javascript-compiler" | "/online-go-compiler" | "/online-rust-compiler" | "/*";
  };
  "routes/_marketing._index.tsx": {
    id: "routes/_marketing._index";
    page: "/";
  };
  "routes/_marketing.$lang.tsx": {
    id: "seo-compiler-c";
    page: "/online-c-compiler";
  } | {
    id: "seo-compiler-cpp";
    page: "/online-cpp-compiler";
  } | {
    id: "seo-compiler-python";
    page: "/online-python-compiler";
  } | {
    id: "seo-compiler-java";
    page: "/online-java-compiler";
  } | {
    id: "seo-compiler-javascript";
    page: "/online-javascript-compiler";
  } | {
    id: "seo-compiler-go";
    page: "/online-go-compiler";
  } | {
    id: "seo-compiler-rust";
    page: "/online-rust-compiler";
  };
  "routes/_editor.editor.tsx": {
    id: "routes/_editor.editor";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_marketing._index": typeof import("./app/routes/_marketing._index.tsx");
  "seo-compiler-c": typeof import("./app/routes/_marketing.$lang.tsx");
  "seo-compiler-cpp": typeof import("./app/routes/_marketing.$lang.tsx");
  "seo-compiler-python": typeof import("./app/routes/_marketing.$lang.tsx");
  "seo-compiler-java": typeof import("./app/routes/_marketing.$lang.tsx");
  "seo-compiler-javascript": typeof import("./app/routes/_marketing.$lang.tsx");
  "seo-compiler-go": typeof import("./app/routes/_marketing.$lang.tsx");
  "seo-compiler-rust": typeof import("./app/routes/_marketing.$lang.tsx");
  "routes/_editor.editor": typeof import("./app/routes/_editor.editor.tsx");
};