"""Add execution log indexes

Revision ID: 08f5e64cadbb
Revises: e123456789ab
Create Date: 2026-07-26 12:12:44.044415

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "08f5e64cadbb"
down_revision: Union[str, Sequence[str], None] = "e123456789ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_execution_logs_status"), "execution_logs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_execution_logs_language"), "execution_logs", ["language"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_execution_logs_language"), table_name="execution_logs")
    op.drop_index(op.f("ix_execution_logs_status"), table_name="execution_logs")
    # ### end Alembic commands ###
