"""add_feedback_error_models

Revision ID: 216639a05be9
Revises: b28df52aca83
Create Date: 2026-07-11 19:45:50.191897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216639a05be9'
down_revision: Union[str, Sequence[str], None] = 'b28df52aca83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.Enum('BUG', 'FEATURE', 'UI', 'PERFORMANCE', 'SECURITY', 'SUGGESTION', 'QUESTION', 'OTHER', name='feedbackcategory'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='feedbackpriority'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('browser_info', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('current_route', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_REVIEW', 'PLANNED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='feedbackstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('system_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_errors_user_id'), 'system_errors', ['user_id'], unique=False)
    op.create_unique_constraint('uq_file_versions_file_version', 'file_versions', ['file_id', 'version_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_file_versions_file_version', 'file_versions', type_='unique')
    op.drop_index(op.f('ix_system_errors_user_id'), table_name='system_errors')
    op.drop_table('system_errors')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
