"""Add complete maintenance mode fields

Revision ID: 49063a496415
Revises: d1630cad1ccc
Create Date: 2026-07-13 05:44:47.048375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49063a496415"
down_revision: Union[str, Sequence[str], None] = "d1630cad1ccc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # These were already created in an earlier migration (62ea23d7a4a9)
    # op.add_column('system_settings', sa.Column('maintenance_mode', sa.Boolean(), server_default='false', nullable=False))
    # op.add_column('system_settings', sa.Column('maintenance_message', sa.String(), nullable=True))
    # op.add_column('system_settings', sa.Column('maintenance_end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "system_settings",
        sa.Column(
            "maintenance_allow_admin_access",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
    )
    op.add_column(
        "system_settings",
        sa.Column(
            "maintenance_show_countdown",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
    )
    op.add_column(
        "system_settings",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "system_settings", sa.Column("updated_by_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None, "system_settings", "users", ["updated_by_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "system_settings", type_="foreignkey")
    op.drop_column("system_settings", "updated_by_id")
    op.drop_column("system_settings", "created_at")
    op.drop_column("system_settings", "maintenance_show_countdown")
    op.drop_column("system_settings", "maintenance_allow_admin_access")
    # op.drop_column('system_settings', 'maintenance_end_time')
    # op.drop_column('system_settings', 'maintenance_message')
    # op.drop_column('system_settings', 'maintenance_mode')
    # ### end Alembic commands ###
