"""Add Project model

Revision ID: 62ea23d7a4a9
Revises: 4113d419cc87
Create Date: 2026-07-11 11:50:42.705488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62ea23d7a4a9"
down_revision: Union[str, Sequence[str], None] = "4113d419cc87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("maintenance_mode", sa.Boolean(), nullable=True),
        sa.Column("maintenance_message", sa.String(), nullable=True),
        sa.Column("maintenance_end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("maintenance_type", sa.String(), nullable=True),
        sa.Column("registration_enabled", sa.Boolean(), nullable=True),
        sa.Column("login_enabled", sa.Boolean(), nullable=True),
        sa.Column("read_only_mode", sa.Boolean(), nullable=True),
        sa.Column("announcement_enabled", sa.Boolean(), nullable=True),
        sa.Column("announcement_message", sa.String(), nullable=True),
        sa.Column("announcement_color", sa.String(), nullable=True),
        sa.Column("default_theme", sa.String(), nullable=True),
        sa.Column("supported_languages", sa.JSON(), nullable=True),
        sa.Column("feature_flags", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("USER", "MODERATOR", "ADMIN", "SUPER_ADMIN", name="roleenum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "SUSPENDED",
                "BANNED",
                "PENDING_VERIFICATION",
                name="statusenum",
            ),
            nullable=False,
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("PRIVATE", "UNLISTED", "PUBLIC", name="projectvisibilityenum"),
            nullable=False,
        ),
        sa.Column("favorite", sa.Boolean(), nullable=True),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(
        "ix_projects_owner_id_updated_at",
        "projects",
        ["owner_id", "updated_at"],
        unique=False,
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=False)
    op.create_index(
        op.f("ix_projects_visibility"), "projects", ["visibility"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_visibility"), table_name="projects")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index("ix_projects_owner_id_updated_at", table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("system_settings")
    # ### end Alembic commands ###
