"""add_github_repo_url

Revision ID: 7ca384dc5d9d
Revises: c997001738a6
Create Date: 2026-07-14 17:43:33.938708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca384dc5d9d'
down_revision: Union[str, Sequence[str], None] = 'c997001738a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_repo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_repo_url')
    # ### end Alembic commands ###
