"""Add user fields and fix project cascade

Revision ID: ac50ec175399
Revises: 2e3e3688f3f7
Create Date: 2026-07-12 02:46:23.721039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac50ec175399'
down_revision: Union[str, Sequence[str], None] = '2e3e3688f3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('permissions_preview', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions_preview')
    op.drop_column('users', 'notes')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
