"""execution_logs_and_admin_updates

Revision ID: b6d06df803b6
Revises: 57b21022edfc
Create Date: 2026-07-12 01:13:44.158692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6d06df803b6"
down_revision: Union[str, Sequence[str], None] = "57b21022edfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUCCESS",
                "COMPILE_ERROR",
                "RUNTIME_ERROR",
                "TIMEOUT",
                "SYSTEM_ERROR",
                name="executionstatus",
            ),
            nullable=False,
        ),
        sa.Column("execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_logs_created_at"),
        "execution_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_logs_project_id"),
        "execution_logs",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_logs_user_id"), "execution_logs", ["user_id"], unique=False
    )
    op.add_column("feedback", sa.Column("rating", sa.Integer(), nullable=True))
    op.add_column("feedback", sa.Column("assigned_to", sa.Uuid(), nullable=True))
    op.add_column(
        "feedback", sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("feedback", sa.Column("admin_reply", sa.Text(), nullable=True))
    op.create_foreign_key(
        None, "feedback", "users", ["assigned_to"], ["id"], ondelete="SET NULL"
    )

    # Create enum type explicitly
    from sqlalchemy.dialects import postgresql

    errortypeenum = postgresql.ENUM(
        "HTTP_500",
        "HTTP_404",
        "HTTP_403",
        "HTTP_401",
        "COMPILER",
        "RUNTIME",
        "DOCKER",
        "EXECUTION",
        "WEBSOCKET",
        "DATABASE",
        "UNKNOWN",
        name="errortypeenum",
    )
    errortypeenum.create(op.get_bind())

    op.add_column(
        "system_errors",
        sa.Column(
            "error_type",
            sa.Enum(
                "HTTP_500",
                "HTTP_404",
                "HTTP_403",
                "HTTP_401",
                "COMPILER",
                "RUNTIME",
                "DOCKER",
                "EXECUTION",
                "WEBSOCKET",
                "DATABASE",
                "UNKNOWN",
                name="errortypeenum",
            ),
            nullable=False,
            server_default="UNKNOWN",
        ),
    )
    op.add_column(
        "system_errors", sa.Column("message", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_errors", "message")
    op.drop_column("system_errors", "error_type")
    op.drop_constraint(None, "feedback", type_="foreignkey")
    op.drop_column("feedback", "admin_reply")
    op.drop_column("feedback", "resolved_at")
    op.drop_column("feedback", "assigned_to")
    op.drop_column("feedback", "rating")
    op.drop_index(op.f("ix_execution_logs_user_id"), table_name="execution_logs")
    op.drop_index(op.f("ix_execution_logs_project_id"), table_name="execution_logs")
    op.drop_index(op.f("ix_execution_logs_created_at"), table_name="execution_logs")
    op.drop_table("execution_logs")

    # Drop enum type explicitly
    op.execute("DROP TYPE errortypeenum")
    # ### end Alembic commands ###
