"""Make booleans non-nullable

Revision ID: b7d69d7cef28
Revises: ac50ec175399
Create Date: 2026-07-12 03:11:18.938615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d69d7cef28'
down_revision: Union[str, Sequence[str], None] = 'ac50ec175399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE projects SET favorite = false WHERE favorite IS NULL")
    op.execute("UPDATE system_settings SET maintenance_mode = false WHERE maintenance_mode IS NULL")
    op.execute("UPDATE system_settings SET registration_enabled = true WHERE registration_enabled IS NULL")
    op.execute("UPDATE system_settings SET login_enabled = true WHERE login_enabled IS NULL")
    op.execute("UPDATE system_settings SET read_only_mode = false WHERE read_only_mode IS NULL")
    op.execute("UPDATE system_settings SET announcement_enabled = false WHERE announcement_enabled IS NULL")
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    op.execute("UPDATE users SET is_deleted = false WHERE is_deleted IS NULL")
    op.execute("UPDATE users SET must_change_password = false WHERE must_change_password IS NULL")
    
    op.alter_column('projects', 'favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_settings', 'maintenance_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_settings', 'registration_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_settings', 'login_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_settings', 'read_only_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_settings', 'announcement_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_settings', 'announcement_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_settings', 'read_only_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_settings', 'login_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_settings', 'registration_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_settings', 'maintenance_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('projects', 'favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
