"""Add missing fields

Revision ID: d1630cad1ccc
Revises: b7d69d7cef28
Create Date: 2026-07-12 10:40:50.860585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1630cad1ccc"
down_revision: Union[str, Sequence[str], None] = "b7d69d7cef28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_settings",
        sa.Column(
            "max_execution_time_seconds",
            sa.Integer(),
            server_default="30",
            nullable=False,
        ),
    )
    op.add_column(
        "system_settings",
        sa.Column("max_memory_mb", sa.Integer(), server_default="256", nullable=False),
    )
    op.add_column(
        "system_settings",
        sa.Column(
            "max_file_size_mb", sa.Integer(), server_default="10", nullable=False
        ),
    )
    op.add_column(
        "system_settings",
        sa.Column(
            "max_projects_per_user", sa.Integer(), server_default="10", nullable=False
        ),
    )
    op.add_column(
        "system_settings",
        sa.Column(
            "rate_limit_per_minute", sa.Integer(), server_default="100", nullable=False
        ),
    )
    op.add_column("system_settings", sa.Column("smtp_host", sa.String(), nullable=True))
    op.add_column(
        "system_settings",
        sa.Column("smtp_port", sa.Integer(), server_default="587", nullable=False),
    )
    op.add_column("system_settings", sa.Column("smtp_user", sa.String(), nullable=True))
    op.add_column("system_settings", sa.Column("smtp_pass", sa.String(), nullable=True))
    op.add_column(
        "system_settings",
        sa.Column(
            "smtp_from_name",
            sa.String(),
            server_default="Hamara Editor",
            nullable=False,
        ),
    )
    op.add_column(
        "system_settings", sa.Column("smtp_from_email", sa.String(), nullable=True)
    )
    op.add_column(
        "system_settings",
        sa.Column("smtp_tls", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "system_settings",
        sa.Column("smtp_ssl", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_settings", "smtp_ssl")
    op.drop_column("system_settings", "smtp_tls")
    op.drop_column("system_settings", "smtp_from_email")
    op.drop_column("system_settings", "smtp_from_name")
    op.drop_column("system_settings", "smtp_pass")
    op.drop_column("system_settings", "smtp_user")
    op.drop_column("system_settings", "smtp_port")
    op.drop_column("system_settings", "smtp_host")
    op.drop_column("system_settings", "rate_limit_per_minute")
    op.drop_column("system_settings", "max_projects_per_user")
    op.drop_column("system_settings", "max_file_size_mb")
    op.drop_column("system_settings", "max_memory_mb")
    op.drop_column("system_settings", "max_execution_time_seconds")
    # ### end Alembic commands ###
